%%%
  VERSION:1
  LANGUAGE:ENGLISH
%%%

MODULE mAUTODESK

  PERS speeddata v12:=[12,500,5000,1000];
  PERS speeddata v16:=[16,500,5000,1000];
  PERS speeddata v17:=[17,500,5000,1000];
  PERS speeddata v35:=[35,500,5000,1000];

  PROC main()
    ! Generated by AUTODESK Fusion CAM 2604.1.48
    ! Creation date: 23/10/2025 09:29:59

    ! Acceleration and jerk/ramp (percentage)
    AccSet 20,20;

    ! Configurations
    ConfJ\On;
    ConfL\Off;

    ! Load Tool
    !Tool_Change Extruder1;

    ! Spindle On/Speed
    !Spindle_ON 0;

    p1001_1;
    p1001_2;
    p1001_3;
    p1001_4;
    p1001_5;
    p1001_6;
    p1001_7;
    p1001_8;
    p1001_9;
    p1001_10;
    p1001_11;
    p1001_12;
    p1001_13;
    p1001_14;
    p1001_15;
    p1001_16;
    p1001_17;
    p1001_18;
    p1001_19;
    p1001_20;
    p1001_21;
    p1001_22;
    p1001_23;
    p1001_24;
    p1001_25;

    ! Spindle Off
    !Spindle_OFF;

    ConfJ\On;
    ConfL\On;
    Stop;
  ENDPROC
ENDMODULE
